// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 17.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HttpClientCode
{
    using Fiddler;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class GenerateCode : GenerateCodeBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using (var httpClient = new HttpClient())\r\n{\r\n\tvar uriBuilder = new UriBuilder(\"");
            
            #line 10 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"
 Write(uri); 
            
            #line default
            #line hidden
            this.Write("\");\r\n\t");
            
            #line 11 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"

	if(httpmethod.ToUpper()=="GET")
	{
	
            
            #line default
            #line hidden
            this.Write("\tvar httpRequestMessage = new HttpRequestMessage(HttpMethod.Get, uriBuilder.ToStr" +
                    "ing());\r\n\t");
            
            #line 16 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"
 
	} 
	
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 19 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"

	if(httpmethod.ToUpper()=="POST")
	{
	
            
            #line default
            #line hidden
            this.Write("\tvar httpRequestMessage = new HttpRequestMessage(HttpMethod.Post, uriBuilder.ToSt" +
                    "ring());\r\n\t");
            
            #line 24 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"
 
	} 
	
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 27 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"

	foreach (var item in headers)
	{
		if(item.Key.Equals("Content-Type", StringComparison.OrdinalIgnoreCase))
		{
	
            
            #line default
            #line hidden
            this.Write("\thttpRequestMessage.Content=new StringContent(\"");
            
            #line 33 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"
 Write(item.Value.ToString()); 
            
            #line default
            #line hidden
            this.Write("\");\r\n\t");
            
            #line 34 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"

		}
		else if(item.Key.Equals("Content-Length", StringComparison.OrdinalIgnoreCase))
		{
			continue;
		}
		else
		{
	
            
            #line default
            #line hidden
            this.Write("\thttpRequestMessage.Headers.Add(\"");
            
            #line 43 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"
 Write(item.Key.ToString()); 
            
            #line default
            #line hidden
            this.Write("\",\"");
            
            #line 43 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"
 Write(item.Value.ToString()); 
            
            #line default
            #line hidden
            this.Write("\");\r\n\t");
            
            #line 44 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"

		}
	}
	
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 48 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"

	if(bodies.Count > 0)
	{
	
            
            #line default
            #line hidden
            this.Write("\tvar values = new Dictionary<string, string>();\r\n\t");
            
            #line 53 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"

	foreach (var item in bodies)
	{
		if(encodeparam)
		{
	
            
            #line default
            #line hidden
            this.Write("\tvalues.Add(\"");
            
            #line 59 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"
 Write(item.Key.ToString()); 
            
            #line default
            #line hidden
            this.Write("\",System.Web.HttpUtility.UrlDecode(\"");
            
            #line 59 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"
 Write(item.Value.ToString()); 
            
            #line default
            #line hidden
            this.Write("\"));\r\n\t");
            
            #line 60 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"

		}
		else
		{
	
            
            #line default
            #line hidden
            this.Write("\tvalues.Add(\"");
            
            #line 65 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"
 Write(item.Key.ToString()); 
            
            #line default
            #line hidden
            this.Write("\",\"");
            
            #line 65 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"
 Write(item.Value.ToString()); 
            
            #line default
            #line hidden
            this.Write("\");\r\n\t");
            
            #line 66 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"

		}
	}
	
            
            #line default
            #line hidden
            this.Write("\tvar content = new FormUrlEncodedContent(values);\r\n\thttpRequestMessage.Content = " +
                    "content;\r\n\t");
            
            #line 72 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"
 
	}	
	
            
            #line default
            #line hidden
            this.Write("\tvar httpResponseMessage = await httpClient.SendAsync(httpRequestMessage);\r\n    v" +
                    "ar httpContent = httpResponseMessage.Content;\r\n    string result = await httpRes" +
                    "ponseMessage.Content.ReadAsStringAsync();\r\n\t//Console.WriteLine(result);\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\Lancc\Source\Repos\HttpClientCode\GenerateCode.tt"

private string _uriField;

/// <summary>
/// Access the uri parameter of the template.
/// </summary>
private string uri
{
    get
    {
        return this._uriField;
    }
}

private string _httpmethodField;

/// <summary>
/// Access the httpmethod parameter of the template.
/// </summary>
private string httpmethod
{
    get
    {
        return this._httpmethodField;
    }
}

private global::System.Collections.Generic.Dictionary<string,string> _headersField;

/// <summary>
/// Access the headers parameter of the template.
/// </summary>
private global::System.Collections.Generic.Dictionary<string,string> headers
{
    get
    {
        return this._headersField;
    }
}

private global::System.Collections.Generic.Dictionary<string,string> _bodiesField;

/// <summary>
/// Access the bodies parameter of the template.
/// </summary>
private global::System.Collections.Generic.Dictionary<string,string> bodies
{
    get
    {
        return this._bodiesField;
    }
}

private bool _encodeparamField;

/// <summary>
/// Access the encodeparam parameter of the template.
/// </summary>
private bool encodeparam
{
    get
    {
        return this._encodeparamField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool uriValueAcquired = false;
if (this.Session.ContainsKey("uri"))
{
    this._uriField = ((string)(this.Session["uri"]));
    uriValueAcquired = true;
}
if ((uriValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("uri");
    if ((data != null))
    {
        this._uriField = ((string)(data));
    }
}
bool httpmethodValueAcquired = false;
if (this.Session.ContainsKey("httpmethod"))
{
    this._httpmethodField = ((string)(this.Session["httpmethod"]));
    httpmethodValueAcquired = true;
}
if ((httpmethodValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("httpmethod");
    if ((data != null))
    {
        this._httpmethodField = ((string)(data));
    }
}
bool headersValueAcquired = false;
if (this.Session.ContainsKey("headers"))
{
    this._headersField = ((global::System.Collections.Generic.Dictionary<string,string>)(this.Session["headers"]));
    headersValueAcquired = true;
}
if ((headersValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("headers");
    if ((data != null))
    {
        this._headersField = ((global::System.Collections.Generic.Dictionary<string,string>)(data));
    }
}
bool bodiesValueAcquired = false;
if (this.Session.ContainsKey("bodies"))
{
    this._bodiesField = ((global::System.Collections.Generic.Dictionary<string,string>)(this.Session["bodies"]));
    bodiesValueAcquired = true;
}
if ((bodiesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("bodies");
    if ((data != null))
    {
        this._bodiesField = ((global::System.Collections.Generic.Dictionary<string,string>)(data));
    }
}
bool encodeparamValueAcquired = false;
if (this.Session.ContainsKey("encodeparam"))
{
    this._encodeparamField = ((bool)(this.Session["encodeparam"]));
    encodeparamValueAcquired = true;
}
if ((encodeparamValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("encodeparam");
    if ((data != null))
    {
        this._encodeparamField = ((bool)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class GenerateCodeBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
